### ISSUE TITLE
WITHDRAWAL MODULE

### ISSUE THREAD

**Issue by hongkheng25** [hongkheng25/sehci_week9lab7b#3]
Link for references:
https://www.mcis.my/Customer-Care/Customer-Service/Customer-Service-Document/CIMB_ATMCDM.aspx

**Comment by hongkheng25** [comment]
Latest References (for Withdrawal):
https://youtu.be/OS7WRkRAnmI

**Comment by owleaglegoat** [comment]
**WITHDRAWAL MODULE** 

_AFTER MENU INTERFACE TO THE END_

![Slide12](https://user-images.githubusercontent.com/76484370/200040765-fc138eab-b109-4475-b951-fba282044db8.PNG)
![Slide13](https://user-images.githubusercontent.com/76484370/200040773-b989786b-c979-4129-9c22-cf33681359f1.PNG)
![Slide14](https://user-images.githubusercontent.com/76484370/200040785-76f801ec-13c1-41fd-820a-d2557c4a2fb1.PNG)
![Slide15](https://user-images.githubusercontent.com/76484370/200040789-fe3fe9e3-94e3-4b0f-adbb-b06ea54906c0.PNG)
![Slide16](https://user-images.githubusercontent.com/76484370/200040794-3872aa20-fa26-4e57-8bd9-8fdd29fa7782.PNG)
![Slide17](https://user-images.githubusercontent.com/76484370/200040796-62f155a2-b7fa-485d-a1f0-761395372758.PNG)
![Slide18](https://user-images.githubusercontent.com/76484370/200040799-289c81b1-c0d8-43bf-ba64-5f68112a84c1.PNG)
![Slide19](https://user-images.githubusercontent.com/76484370/200040801-1bfafd46-73b8-4ada-b118-dd9be7b5ea2a.PNG)

**Comment by owleaglegoat** [comment]
Closing the issue
