### ISSUE TITLE
INSTANT TRANSFER MODULE

### ISSUE THREAD

**Issue by hongkheng25** [hongkheng25/sehci_week9lab7b#4]
Link for references:
https://www.mcis.my/Customer-Care/Customer-Service/Customer-Service-Document/CIMB_ATMCDM.aspx

**Comment by nigelgks** [comment]
INSTANT TRANSFER MODULE - DONE

AFTER MENU INTERFACE TO THE END

![Slide8](https://user-images.githubusercontent.com/72488393/199886527-a8dc5157-0c51-4a8a-8459-835c0186630d.JPG)
![Slide9](https://user-images.githubusercontent.com/72488393/199886534-573901f6-0c42-4b0b-841e-0f1b87f257a5.JPG)
![Slide10](https://user-images.githubusercontent.com/72488393/199886535-f95d8484-fab9-4e7d-8601-719cb76182ce.JPG)
![Slide11](https://user-images.githubusercontent.com/72488393/199886536-ee92e3bb-84cc-42ce-b433-5b05c18f95d2.JPG)
![Slide12](https://user-images.githubusercontent.com/72488393/199886538-40f713a2-27da-4c14-ba48-0e9856644357.JPG)
![Slide13](https://user-images.githubusercontent.com/72488393/199886539-024f3618-1a18-4f88-849c-dcd327b9fc90.JPG)
![Slide14](https://user-images.githubusercontent.com/72488393/199886541-165c9917-29aa-44f8-91d3-829cf9908469.JPG)
