### ISSUE TITLE
LOAN REPAYMENT / FINANCING MODULE 

### ISSUE THREAD

**Issue by hongkheng25** [hongkheng25/sehci_week9lab7b#5]
Link for references:
https://www.mcis.my/Customer-Care/Customer-Service/Customer-Service-Document/CIMB_ATMCDM.aspx

**Comment by YongQiChang** [comment]
UI for Loan and Financing (Hire Purchase)
![Picture1](https://user-images.githubusercontent.com/117340002/199915774-d954dc1c-4929-4eba-abe8-6214fe1918f4.png)
![Picture2](https://user-images.githubusercontent.com/117340002/199915778-0565f075-63c3-432a-8d59-9bbf5aa418d2.png)
![Picture3](https://user-images.githubusercontent.com/117340002/199915784-c2296959-609c-461f-85e0-d3e319480f47.png)
![Picture4](https://user-images.githubusercontent.com/117340002/199915789-0fc6d352-ca48-4d0e-80c9-7bead4affd7c.png)
![Picture5](https://user-images.githubusercontent.com/117340002/199915801-00514a85-f16c-4633-b77f-37ebeb083d70.png)
![Picture6](https://user-images.githubusercontent.com/117340002/199915808-c2248218-5eb7-487c-bf2e-9bff42186553.png)
![Picture7](https://user-images.githubusercontent.com/117340002/199915820-6cd69d6a-706c-4048-840c-0dea3df7aa81.png)
![Picture9](https://user-images.githubusercontent.com/117340002/199915830-9d4cbd81-6fc9-422e-8b9c-d078eb68152d.png)
